=== BourjijKiller/XML/XML_Schema/livre/livre.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
		targetNamespace="http://www.univ-amu.fr/XML/livre"
		xmlns:liv="http://www.univ-amu.fr/XML/livre"
		xmlns:com="http://www.univ-amu.fr/XML/commun"
		elementFormDefault="qualified"
		attributeFormDefault="unqualified">
		
		<!-- Import du modèle de document commun.xsd -->
		<xs:import namespace="http://www.univ-amu.fr/XML/commun" schemaLocation="../commun/commun.xsd"/>
		
		<xs:annotation>
			<xs:documentation>
				Une introduction est un ensemble de paragraphe (au moins 1)
			</xs:documentation>
		</xs:annotation>
		<xs:element name="introduction">
			<xs:complexType>
				<!-- On peut avoir 1..n paragraphe(s) -->
				<xs:sequence minOccurs="1" maxOccurs="unbounded">
					<!-- Un paragraphe est un élément mixte constitué de texte et éventuellement de renvois vers des leçons -->
					<xs:element ref="liv:paragraphe"/>
				</xs:sequence>
			</xs:complexType>
		</xs:element>
		
		<xs:annotation>
			<xs:documentation>
				Un paragraphe est un élément mixte constitué de texte et éventuellement d'un ou plusieurs renvois vers une leçon
			</xs:documentation>
		</xs:annotation>
		<xs:element name="paragraphe">
			<!-- Mixed = true -> élément mixte -->
			<xs:complexType mixed="true">
				<xs:attribute name="référence" type="xs:IDREFS" use="optional"/>
			</xs:complexType>
		</xs:element>
		
		<xs:annotation>
			<xs:documentation>
				Un titre est une chaîne de caractères
			</xs:documentation>
		</xs:annotation>
		<xs:element name="titre" type="xs:string"/>
		
		<xs:annotation>
			<xs:documentation>
				Un numéro est un entier strictement positif
			</xs:documentation>
		</xs:annotation>
		<xs:element name="numéro" type="xs:nonNegativeInteger"/>
		
		<xs:annotation>
			<xs:documentation>
				Un livre est décrit par un titre, un ou plusieurs auteurs, un éditeur, une année d'édition, un numéro ISBN et un ensemble de leçons
				(au moins une)
			</xs:documentation>
		</xs:annotation>
		
		<xs:element name="livre">
			<xs:complexType>
				<xs:sequence>
					<!-- Un titre est une chaîne de caractères -->
					<xs:element ref="liv:titre"/>
					<!-- Une liste d'auteurs peut contenir 1 ou plusieurs auteur(s) -->
					<xs:element name="auteurs">
						<xs:complexType>
							<xs:sequence minOccurs="1" maxOccurs="unbounded">
								<!-- Un auteur est une personne (Groupe personne commun.xsd) -->
								<xs:element name="auteur">
									<xs:complexType>
										<xs:group ref="com:personne"/>
									</xs:complexType>
								</xs:element>
							</xs:sequence>
						</xs:complexType>
					</xs:element>
					<!-- Un éditeur est une chaîne de caractères -->
					<xs:element name="éditeur" type="xs:string"/>
					<!-- Une année d’édition est un entier strictement positif sur 4 chiffres -->
					<xs:element name="année-édition">
						<xs:simpleType>
							<xs:restriction base="xs:nonNegativeInteger">
								<xs:pattern value="[\d]{4}"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:element>
					
					<!-- Une leçon est décrite par un numéro,
						un titre, une introduction,
						un ensemble de chapitres (au moins un),
						et un ensemble d'exercices (au moins 1) -->
					<xs:element name="lecon" minOccurs="1" maxOccurs="unbounded">
						<xs:complexType>
							<xs:sequence>
								<!-- Un numéro est un entier strictement positif -->
								<xs:element ref="liv:numéro"/>
								<!-- Un titre est une chaîne de caractères -->
								<xs:element ref="liv:titre"/>
								<!-- Une introduction est un ensemble de paragraphes -->
								<xs:element ref="liv:introduction"/>
								<!-- Un chapitre est constitué d'un titre, d'une introduction et de sections (au moins une)
									On fait référence aux éléments titre et introduction afin de factoriser le code -->
								<xs:element name="chapitres">
									<xs:complexType>
										<xs:sequence>
											<xs:element name="chapitre" minOccurs="1" maxOccurs="unbounded">
												<xs:complexType>
													<xs:sequence>
													<!-- Référence à l'élément global titre -->
														<xs:element ref="liv:titre"/>
														<!-- Référence à l'élément global introduction -->
														<xs:element ref="liv:introduction"/>
														<!-- Une liste de sections est composée d'une ou plusieurs section(s) -->
														<xs:element name="sections" minOccurs="1" maxOccurs="unbounded">
															<xs:complexType>
																<xs:sequence>
																	<!-- Une section est constitué d'un titre et d'un ou plusieurs paragraphes -->
																	<!-- On peut avoir 1..n section(s) -->
																	<xs:element name="section" minOccurs="1" maxOccurs="unbounded">
																		<xs:complexType>
																			<xs:sequence>
																				<xs:element ref="liv:titre"/>
																				<!-- On peut avoir 1..n section(s) -->
																				<xs:element ref="liv:paragraphe" minOccurs="1" maxOccurs="unbounded"/>
																			</xs:sequence>
																		</xs:complexType>
																	</xs:element>
																</xs:sequence>
															</xs:complexType>
														</xs:element>
													</xs:sequence>
												</xs:complexType>
											</xs:element>
										</xs:sequence>
									</xs:complexType>
								</xs:element>
								<!-- Un ensemble d'exercices est constitué d'un ou plusieurs exercice(s) -->
								<xs:element name="exercices">
									<xs:complexType>
										<!-- On peut avoir 1..n exercice(s) -->
										<xs:sequence minOccurs="1" maxOccurs="unbounded">
											<!-- Un exercice est constituée d'un numéro, d'un QCM ainsi que d'un corrigé -->
											<xs:element name="exercice">
												<xs:complexType>
													<xs:sequence>
														<!-- Référence à l'élément numéro déclaré globalement -->
														<xs:element ref="liv:numéro"/>
														<!-- Un QCM est composé d'un énoncé et d'au moins 2 propositions de réponses -->
														<xs:element name="QCM">
															<xs:complexType>
																<xs:sequence>
																	<xs:element name="énoncé" type="xs:string"/>
																	<xs:element name="proposition-réponse" minOccurs="2" maxOccurs="unbounded" type="xs:string"/>
																</xs:sequence>
															</xs:complexType>
														</xs:element>
														<!-- Un corrigé désigne la ou les propositions de réponses valides parmi celles qui sont faites dans les propositions de réponses -->
														<xs:element name="corrigé" type="xs:string"/>
													</xs:sequence>
												</xs:complexType>
											</xs:element>
										</xs:sequence>
									</xs:complexType>
								</xs:element>
							</xs:sequence>
							<!-- Une leçon est identifié de manière unique -->
							<xs:attribute name="id" use="required" type="xs:ID"/>
						</xs:complexType>
					</xs:element>
				</xs:sequence>
				<!-- Un numéro ISBN est un entier strictement positif sur 13 chiffres -->
				<xs:attribute name="ISBN" use="required">
					<xs:simpleType>
						<xs:restriction base="xs:nonNegativeInteger">
							<xs:pattern value="[\d]{13}"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:attribute>
			</xs:complexType>
		</xs:element>
</xs:schema>

=== BourjijKiller/XML/XML_Schema/livre/livre.xml
<?xml version="1.0" encoding="UTF-8"?>
<liv:livre ISBN="1234567890123"
			xmlns:com="http://www.univ-amu.fr/XML/commun"
			xmlns:liv="http://www.univ-amu.fr/XML/livre"
			xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
			xsi:schemaLocation="http://www.univ-amu.fr/XML/livre livre.xsd ">
			
	<liv:titre>Titeuf</liv:titre>
		<liv:auteurs>
			<liv:auteur>
				<com:civilité>Mlle</com:civilité>
				<com:prénom-usuel>Pauline</com:prénom-usuel>
				<com:prénom-complémentaire>Lila</com:prénom-complémentaire>
				<com:nom>azerty</com:nom>
			</liv:auteur>
			<liv:auteur>
				<com:civilité>M.</com:civilité>
				<com:prénom-usuel>Samuel</com:prénom-usuel>
				<com:nom>Entezam</com:nom>
			</liv:auteur>
		</liv:auteurs>
		<liv:éditeur>Entezam Samuel</liv:éditeur>
		<liv:année-édition>2014</liv:année-édition>
		<liv:lecon id="lecon-1">
			<liv:numéro>1</liv:numéro>
			<liv:titre>Apprendre le XML</liv:titre>
			<liv:introduction>
				<liv:paragraphe>
					Le Lorem Ipsum est simplement du faux texte employé dans la composition et la mise en page avant impression. Le Lorem Ipsum est le faux texte standard de l'imprimerie depuis les années 1500, quand un imprimeur anonyme assembla ensemble des morceaux de texte pour réaliser un livre spécimen de polices de texte.
				</liv:paragraphe>
				<liv:paragraphe>
					 Il n'a pas fait que survivre cinq siècles, mais s'est aussi adapté à la bureautique informatique, sans que son contenu n'en soit modifié.
				</liv:paragraphe>
			</liv:introduction>
			<liv:chapitres>
				<liv:chapitre>
					<liv:titre>Chapitre n°1 : Historique du XML</liv:titre>
					<liv:introduction>
						<liv:paragraphe>
							Il a été popularisé dans les années 1960 grâce à la vente de feuilles Letraset contenant des passages du Lorem Ipsum, et, plus récemment, par son inclusion dans des applications de mise en page de texte, comme Aldus PageMaker.
						</liv:paragraphe>
					</liv:introduction>
					<liv:sections>
						<liv:section>
							<liv:titre>Section 1</liv:titre>
							<liv:paragraphe>
								Un paragraphe qui ne veut rien dire
							</liv:paragraphe>
							<liv:paragraphe>
								Un deuxième paragraphe parlant d'une vallée innondée
							</liv:paragraphe>
							<liv:paragraphe référence="lecon-1">
								On revient au XML
							</liv:paragraphe>
						</liv:section>
					</liv:sections>
				</liv:chapitre>
			</liv:chapitres>
			<liv:exercices>
				<liv:exercice>
					<liv:numéro>1</liv:numéro>
					<liv:QCM>
						<liv:énoncé>Qu'est-ce que MIAGE+ ? </liv:énoncé>
						<liv:proposition-réponse>un BDE</liv:proposition-réponse>
						<liv:proposition-réponse>Une association à but lucratif</liv:proposition-réponse>
						<liv:proposition-réponse>Kashmir Village</liv:proposition-réponse>
					</liv:QCM>
					<liv:corrigé>un BDE</liv:corrigé>
				</liv:exercice>
				<liv:exercice>
					<liv:numéro>2</liv:numéro>
					<liv:QCM>
						<liv:énoncé>Faut-il faire son PHP en cours de Java ?</liv:énoncé>
						<liv:proposition-réponse>Oui</liv:proposition-réponse>
						<liv:proposition-réponse>Non</liv:proposition-réponse>
						<liv:proposition-réponse>Chicken</liv:proposition-réponse>
					</liv:QCM>
					<liv:corrigé>Non</liv:corrigé>
				</liv:exercice>
			</liv:exercices>
		</liv:lecon>
</liv:livre>
