=== BourjijKiller/XML/Espace_De_Nommage/dictionnaire.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!-- Modifiez la DTD dictionnaire.dtd afin que, dans les documents XML basés sur elle, tous les éléments et tous les attributs qui y sont déclarés soient associés à un espace de nommage d’identifiant http://www.univ-amu.fr/XML/dictionnaire et de préfixe dico. -->
<!-- REMARQUE : contrairement à celle du préambule, cette DTD ne contient pas de définitions communes, pouvant être réutilisées indépendamment les unes des autres. On peut donc déclarer l'espace de nommage une seule fois (sur l'élément racine). Il faut par contre toujours penser à l'utiliser à bon escient pour qualifier ce qui doit l'être (ici, uniquement les éléments). -->

<!ELEMENT dico:dictionnaire (dico:entrée)+>
<!ATTLIST dico:dictionnaire
	xmlns:dico CDATA #FIXED "http://www.univ-amu.fr/XML/dictionnaire">

<!ELEMENT dico:entrée (dico:orthographe, (dico:nomPropre | dico:nomCommun | dico:adjectif | dico:verbe | dico:pronomPersonnel | dico:pronomRelatif), dico:prononciation, (dico:renvoi | dico:signification+), dico:expression*, dico:étymologie?)>
<!ATTLIST dico:entrée
	dico:identifiant ID #REQUIRED>

<!ELEMENT dico:orthographe (dico:usuelle, dico:dérivée*)>

<!ELEMENT dico:usuelle (#PCDATA)>

<!ELEMENT dico:dérivée (#PCDATA)>

<!ELEMENT dico:nomPropre EMPTY>

<!ELEMENT dico:nomCommun (dico:genre, dico:nombre)>

<!ELEMENT dico:verbe (dico:groupe, dico:forme)>

<!ELEMENT dico:adjectif (dico:genre, dico:nombre)>

<!ELEMENT dico:pronomPersonnel EMPTY>

<!ELEMENT dico:pronomRelatif EMPTY>

<!ELEMENT dico:genre (dico:annotation*)>
<!ATTLIST dico:genre
	dico:valeur (masculin | féminin | neutre) #REQUIRED>

<!ELEMENT dico:nombre (dico:annotation*)>
<!ATTLIST dico:nombre
	dico:valeur (singulier | pluriel) #REQUIRED>

<!ELEMENT dico:annotation (#PCDATA)>

<!ELEMENT dico:groupe (dico:annotation*)>
<!ATTLIST dico:groupe
	dico:valeur (1er | 2ème | 3ème) #REQUIRED>

<!ELEMENT dico:forme (dico:annotation*)>
<!ATTLIST dico:forme
	dico:valeur (transitif | intransitif | réfléchi) #REQUIRED>

<!ELEMENT dico:prononciation (#PCDATA)>

<!ELEMENT dico:renvoi EMPTY>
<!ATTLIST dico:renvoi
	dico:cible IDREF #REQUIRED>

<!ELEMENT dico:signification (dico:sens, dico:exemple*, dico:traduction*)>
<!ATTLIST dico:signification
	dico:domaine (lang.fam. | lang.cour. | finance | informatique) #REQUIRED>

<!ELEMENT dico:sens (#PCDATA | dico:renvoi)*>

<!ELEMENT dico:exemple (#PCDATA)>

<!ELEMENT dico:traduction (dico:écriture, dico:prononciation, dico:annotation*)>
<!ATTLIST dico:traduction
	dico:langue (anglais | américain | espagnol | italien) #REQUIRED>

<!ELEMENT dico:écriture (#PCDATA)>

<!ELEMENT dico:expression (dico:écriture, dico:sens, dico:exemple*, dico:traduction*)>
<!ATTLIST dico:expression
	dico:domaine (lang.fam. | lang.cour. | finance | informatique) #REQUIRED>

<!ELEMENT dico:étymologie (#PCDATA)>

=== BourjijKiller/XML/Espace_De_Nommage/dictionnaire.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE dico:dictionnaire SYSTEM "dictionnaire.dtd">
<dico:dictionnaire>
	<dico:entrée dico:identifiant="E1">
		<dico:orthographe>
			<dico:usuelle>oignon</dico:usuelle>
			<dico:dérivée>ognon</dico:dérivée>
			<dico:dérivée>onion</dico:dérivée>
		</dico:orthographe>
		<dico:nomCommun>
			<dico:genre dico:valeur="masculin"/>
			<dico:nombre dico:valeur="singulier"/>
		</dico:nomCommun>
		<dico:prononciation>oanion</dico:prononciation>
		<dico:signification dico:domaine="lang.cour.">
			<dico:sens>Plante (liliacée) potagère du genre ail, dont le bulbe, d'une saveur et d'une odeur fortes et piquantes, est très employé en cuisine ; le bulbe lui-même. (L'oignon est une plante bisannuelle bulbeuse très anciennement cultivée.)</dico:sens>
			<dico:traduction dico:langue="espagnol">
				<dico:écriture>cebola</dico:écriture>
				<dico:prononciation>sébola</dico:prononciation>
			</dico:traduction>
		</dico:signification>
		<dico:expression dico:domaine="lang.cour.">
			<dico:écriture>C'est pas tes oignons</dico:écriture>
			<dico:sens>Ce ne sont pas tes affaires, ça ne te concerne pas.</dico:sens>
			<dico:exemple>Mêle toi de tes affaires : ce ne sont pas tes oignons, ça ne regarde que moi !</dico:exemple>
		</dico:expression>
	</dico:entrée>
	<dico:entrée dico:identifiant="E2">
		<dico:orthographe>
			<dico:usuelle>cuisiner</dico:usuelle>
		</dico:orthographe>
		<dico:verbe>
			<dico:groupe dico:valeur="1er"></dico:groupe>
			<dico:forme dico:valeur="transitif"></dico:forme>
		</dico:verbe>
		<dico:prononciation>cuiziné</dico:prononciation>
		<dico:signification dico:domaine="lang.cour.">
			<dico:sens>Préparer et accommoder les aliments de telle sorte qu'ils soient propres à la consommation et agréables au goût</dico:sens>
		</dico:signification>
		<dico:expression dico:domaine="lang.fam.">
			<dico:écriture>Cuisiner quelqu'un</dico:écriture>
			<dico:sens>Interroger quelqu'un</dico:sens>
		</dico:expression>
	</dico:entrée>
	<dico:entrée dico:identifiant="E3">
		<dico:orthographe>
			<dico:usuelle>préparer</dico:usuelle>
		</dico:orthographe>
		<dico:verbe>
			<dico:groupe dico:valeur="1er"></dico:groupe>
			<dico:forme dico:valeur="transitif"></dico:forme>
		</dico:verbe>
		<dico:prononciation>préparé</dico:prononciation>
		<dico:signification dico:domaine="lang.cour.">
			<dico:sens>Choisir, prendre, disposer à l'avance ce qui sera nécessaire pour une opération quelconque</dico:sens>
		</dico:signification>
		<dico:expression dico:domaine="lang.cour.">
			<dico:écriture>Préparer le repas</dico:écriture>
			<dico:sens><dico:renvoi dico:cible="E2"/></dico:sens>
		</dico:expression>
	</dico:entrée>
</dico:dictionnaire>
