=== BourjijKiller/XML/XPath/livre/livre_CI.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns="http://www.univ-amu.fr/XML/livre_ci"
			xmlns:liv="http://www.univ-amu.fr/XML/livre_ci"
			xmlns:xs="http://www.w3.org/2001/XMLSchema"
			xmlns:com="http://www.univ-amu.fr/XML/commun"
			targetNamespace="http://www.univ-amu.fr/XML/livre_ci"
			elementFormDefault="qualified"
			attributeFormDefault="qualified">
			
	<!-- Commun.xsd du prof -->
	<xs:import namespace="http://www.univ-amu.fr/XML/commun" schemaLocation="../../T.P5_XPath/commun/commun.xsd"/>
	<xs:element name="livre">
		<xs:annotation>
			<xs:documentation>Livre à contenu pédagogique</xs:documentation>
		</xs:annotation>
		<xs:complexType mixed="false">
			<xs:sequence>
				<xs:element name="titre" type="xs:string"/>
				<xs:element name="auteur" type="com:personneType" maxOccurs="unbounded"/>
				<xs:element name="éditeur" type="xs:string"/>
				<xs:element name="année" type="xs:gYear"/>
				<xs:element name="leçon" maxOccurs="unbounded">
					<xs:complexType mixed="false">
						<xs:sequence>
							<xs:element name="titre" type="xs:string"/>
							<xs:element ref="liv:introduction"/>
							<xs:element name="chapitre" maxOccurs="unbounded">
								<xs:complexType mixed="false">
									<xs:sequence>
										<xs:element name="titre" type="xs:string"/>
										<xs:element ref="liv:introduction"/>
										<xs:element name="section" maxOccurs="unbounded">
											<xs:complexType mixed="false">
												<xs:sequence>
													<xs:element name="titre" type="xs:string"/>
													<xs:element ref="liv:paragraphe" maxOccurs="unbounded"/>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
								
								<!-- Au sein d'un même chapitre, les sections doivent avoir des titres différents -->
								<xs:unique name="sections-unique">
									<!-- La contrainte d'intégrité cible les sections d'un chapitre -->
									<xs:selector xpath=".//liv:section"/>
									<!-- L'unicité est calculée à partir du titre de chaque sections -->
									<xs:field xpath="./liv:titre"/>
								</xs:unique>
							</xs:element>
							<xs:element name="exercice" maxOccurs="unbounded">
								<xs:complexType mixed="false">
									<xs:sequence>
										<xs:element name="QCM">
											<xs:complexType mixed="false">
												<xs:sequence>
													<xs:element name="énoncé" type="xs:string"/>
													<xs:element name="proposition" minOccurs="2" maxOccurs="unbounded">
														<xs:complexType mixed="false">
															<xs:simpleContent>
																<xs:extension base="xs:string">
																	<xs:attribute name="numéro" type="xs:positiveInteger" use="required"/>
																</xs:extension>
															</xs:simpleContent>
														</xs:complexType>
													</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
										<xs:element name="corrigé">
											<xs:complexType mixed="false">
												<xs:sequence>
													<xs:element name="bonneProposition" maxOccurs="unbounded">
														<xs:complexType mixed="false">
															<xs:attribute name="numéro" type="xs:positiveInteger" use="required"/>
														</xs:complexType>
													</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
									<xs:attribute name="numéro" type="xs:positiveInteger" use="required"/>
								</xs:complexType>
								<xs:key name="proposition-réponse">
									<xs:selector xpath=".//liv:proposition"/>
									<xs:field xpath="./@liv:numéro"/>
								</xs:key>
								
								<xs:keyref name="corrigé" refer="liv:proposition-réponse">
									<xs:selector xpath=".//liv:bonneProposition"/>
									<xs:field xpath="./@liv:numéro"/>
								</xs:keyref>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="numéro" type="xs:positiveInteger" use="required"/>
					</xs:complexType>
					
					<!-- Au sein d'une même leçon, les chapitres doivent être identifiés de façon unique -->
					<xs:unique name="chapitre-unique">
						<!-- La contrainte d'intégrité cible les chapitres d'une leçon -->
						<xs:selector xpath=".//liv:chapitre"/>
						<!-- La donnée de calcul est le titre d'un chapitre -->
						<xs:field xpath="./liv:titre"/>
					</xs:unique>
					
					<!-- Au sein d'une même leçon, les exercices doivent être identifiés de facon unique -->
					<xs:unique name="exercice-unique">
						<!-- La contrainte d'intégrité cible les exercices d'une leçon -->
						<xs:selector xpath=".//liv:exercice"/>
						<!-- La donnée de calcul est le numéro d'une leçon (doit être unique) -->
						<xs:field xpath="./@liv:numéro"/>
					</xs:unique>
				</xs:element>
			</xs:sequence>
			<xs:attribute name="ISBN" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:positiveInteger">
						<xs:pattern value="\d{13}"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
		
		<!-- TODO NE FONCTIONNE PAS -->
		<!-- Au sein d'un même livre, les leçons doivent être identifiées de façon unique
		<xs:unique name="leçon-unique">
			La contrainte d'intégrité vise la leçon
			<xs:selector xpath=".//liv:leçon"/>
			La contrainte d'intégrité est calculée à partir du numéro et du titre du livre
			<xs:field xpath="./liv:titre | ./@liv:numéro"/>
		</xs:unique> -->
		
		<xs:unique name="leçon-unique-titre">
			<xs:selector xpath=".//liv:leçon"/>
			<xs:field xpath="./liv:titre"/>
		</xs:unique>
		
		<xs:unique name="leçon-unique-numéro">
			<xs:selector xpath=".//liv:leçon"/>
			<xs:field xpath="./@liv:numéro"/>
		</xs:unique>
		
		<!-- Au sein d'un livre, les auteurs doivent avoir des couples nom/prénom différents -->
		<xs:unique name="auteur-unique">
			<!-- La contrainte d'intégrité vise les auteurs -->
			<xs:selector xpath=".//liv:auteur"/>
			<!-- On ne peut avoir un couple nom et prénom identique
				Par conséquent, on peut avoir des couples nom identique / prénom différents
				ou encore nom différent / prénom identique
				On met donc en champ calculé le nom et le prénom usuel
			 -->
			<xs:field xpath="./com:nom"/>
			<xs:field xpath="./com:prénomUsuel"/>
		</xs:unique>
		
		<xs:key name="leçon">
			<xs:selector xpath="./liv:leçon"/>
			<xs:field xpath="./liv:titre"/>
			<xs:field xpath="./@liv:numéro"/>
		</xs:key>
		
		<xs:keyref name="leçonIsExist" refer="liv:leçon">
			<xs:selector xpath=".//liv:renvoi"/>
			<xs:field xpath="./@liv:refTitre"/>
			<xs:field xpath="./@liv:refNuméro"/>
		</xs:keyref>
	</xs:element>
	<!-- Déclarations globales -->
	<xs:element name="paragraphe">
		<xs:complexType mixed="true">
			<xs:sequence>
				<xs:element name="renvoi" minOccurs="0" maxOccurs="unbounded">
					<xs:complexType>
						<xs:simpleContent>
							<xs:extension base="xs:string">
								<xs:attribute name="refTitre" type="xs:string" use="required"/>
								<xs:attribute name="refNuméro" type="xs:positiveInteger" use="required"/>
							</xs:extension>
						</xs:simpleContent>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="introduction">
		<xs:complexType mixed="false">
			<xs:sequence>
				<xs:element ref="liv:paragraphe" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== BourjijKiller/XML/XML_Schema/livre/livre_CI.xml
<?xml version="1.0" encoding="UTF-8"?>
<liv:livre liv:ISBN="1234567891234"
			xsi:schemaLocation="http://www.univ-amu.fr/XML/livre_ci livre_CI.xsd"
			xmlns:liv="http://www.univ-amu.fr/XML/livre_ci"
			xmlns:com="http://www.univ-amu.fr/XML/commun"
			xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
			
	<liv:titre>Un bouquin sur XML</liv:titre>
	<liv:auteur>
		<com:civilité>M.</com:civilité>
		<com:prénomUsuel>Philippe</com:prénomUsuel>
		<com:nom>RAMADOUR</com:nom>
	</liv:auteur>
	<!-- Supposé Valide -->
	<liv:auteur>
		<com:civilité>M.</com:civilité>
		<com:prénomUsuel>Pradap</com:prénomUsuel>
		<com:nom>Khan</com:nom>
	</liv:auteur>
	<liv:auteur>
		<com:civilité>Mme</com:civilité>
		<com:prénomUsuel>Karissa</com:prénomUsuel>
		<com:nom>Khan</com:nom>
	</liv:auteur>
	<liv:auteur>
		<com:civilité>M.</com:civilité>
		<com:prénomUsuel>Pradap</com:prénomUsuel>
		<com:nom>Kashmir</com:nom>
	</liv:auteur>
	<!-- Supposé invalide -->
	<!-- <liv:auteur>
		<com:civilité>M.</com:civilité>
		<com:prénomUsuel>Pradap</com:prénomUsuel>
		<com:nom>Khan</com:nom>
	</liv:auteur> -->
	<liv:éditeur>AMU / FEG / ISSG / MIAGE</liv:éditeur>
	<liv:année>2017</liv:année>
	<liv:leçon liv:numéro="1">
		<liv:titre>Introduction à XML</liv:titre>
		<liv:introduction>
			<liv:paragraphe>Pourquoi ce langage ? Quels sont ses avantages ? Quels sont ses principales caractéristiques ?</liv:paragraphe>
		</liv:introduction>
		<liv:chapitre>
			<liv:titre>Les difficultés de la gestion de données structurées</liv:titre>
			<liv:introduction>
				<liv:paragraphe>La gestion de données structurées est éprouvée depuis 50 ans.</liv:paragraphe>
				<liv:paragraphe>Mais, elle apporte un lot de contraintes parfois délicates à appréhender/mettre en oeuvre.</liv:paragraphe>
			</liv:introduction>
			<liv:section>
				<liv:titre>Par rapports aux SGBDR</liv:titre>
				<liv:paragraphe>Difficultés de lisibilité, ...</liv:paragraphe>
				<liv:paragraphe>Modélisation stricte, ...</liv:paragraphe>
			</liv:section>
			<liv:section>
				<liv:titre>Par rapport aux SGBDOO</liv:titre>
				<liv:paragraphe>Difficulté de lisibilité (encore), ...</liv:paragraphe>
				<liv:paragraphe>Lourdeur, ...</liv:paragraphe>
			</liv:section>
		</liv:chapitre>
		<liv:chapitre>
			<liv:titre>Avantages des formalismes semi-structurés</liv:titre>
			<liv:introduction>
				<liv:paragraphe>Moins de recul mais de nombreuses facilités offertes...</liv:paragraphe>
			</liv:introduction>
			<liv:section>
				<liv:titre>Extensibilité du langage</liv:titre>
				<liv:paragraphe>Possibilité de définir ses propres données <liv:renvoi liv:refNuméro="2" liv:refTitre="Le langage XML">(cf. "Le langage XML")</liv:renvoi>.</liv:paragraphe>
			</liv:section>
			<liv:section>
				<liv:titre>Portabilité</liv:titre>
				<liv:paragraphe>Elle est due notamment à la standardisation <liv:renvoi liv:refNuméro="2" liv:refTitre="Le langage XML">(cf. "le langage XML")</liv:renvoi>.</liv:paragraphe>
				<liv:paragraphe>Elle est facilité par la myriade d'outils disponibles.</liv:paragraphe>
			</liv:section>
			<liv:section>
				<liv:titre>Lisibilité</liv:titre>
				<liv:paragraphe>Repose sur l'extensibilité.</liv:paragraphe>
				<liv:paragraphe>Facilite la compréhension humaine.</liv:paragraphe>
			</liv:section>
		</liv:chapitre>
		<liv:exercice liv:numéro="1">
			<liv:QCM>
				<liv:énoncé>XML est un langage...</liv:énoncé>
				<liv:proposition liv:numéro="1">Structuré</liv:proposition>
				<liv:proposition liv:numéro="2">Semi structuré</liv:proposition>
				<liv:proposition liv:numéro="3">Non structuré</liv:proposition>
			</liv:QCM>
			<liv:corrigé>
				<liv:bonneProposition liv:numéro="2"></liv:bonneProposition>
			</liv:corrigé>
		</liv:exercice>
		<liv:exercice liv:numéro="2">
			<liv:QCM>
				<liv:énoncé>Par rapport aux SGBDR, la gestion de données en XML est...</liv:énoncé>
				<liv:proposition liv:numéro="1">Plus stricte</liv:proposition>
				<liv:proposition liv:numéro="2">Moins stricte</liv:proposition>
				<liv:proposition liv:numéro="3">Avantageuse sur des volumes de données de granularité faible à moyenne</liv:proposition>
				<liv:proposition liv:numéro="4">Avantageuse sur des volumes de données élevés à extrêmes (big data)</liv:proposition>
			</liv:QCM>
			<liv:corrigé>
				<liv:bonneProposition liv:numéro="2"/>
				<liv:bonneProposition liv:numéro="3"/>
			</liv:corrigé>
		</liv:exercice>
	</liv:leçon>
	<liv:leçon liv:numéro="2">
		<liv:titre>Le langage XML</liv:titre>
		<liv:introduction>
			<liv:paragraphe>XML est un langage qui s'impose de plus en plus (malgré la présence de "concurrents" tels que JSON).</liv:paragraphe>
		</liv:introduction>
		<liv:chapitre>
			<liv:titre>Le petit historique</liv:titre>
			<liv:introduction>
				<liv:paragraphe>Evolution des langages semi-structurés depuis SGML...</liv:paragraphe>
			</liv:introduction>
			<liv:section>
				<liv:titre>SGML</liv:titre>
				<liv:paragraphe>Le "premier vrai" langage semi-structuré.</liv:paragraphe>
				<liv:paragraphe>Merci au monde de l'édition :-)</liv:paragraphe>
			</liv:section>
			<liv:section>
				<liv:titre>HTML</liv:titre>
				<liv:paragraphe>La popularisation de la semi-structuration.</liv:paragraphe>
				<liv:paragraphe>Merci au Web :-)</liv:paragraphe>
			</liv:section>
			<liv:section>
				<liv:titre>XML</liv:titre>
				<liv:paragraphe>La vague de la semi-structuration.</liv:paragraphe>
				<liv:paragraphe>Merci à la professionnalisation du Web :-)</liv:paragraphe>
			</liv:section>
		</liv:chapitre>
		<liv:chapitre>
			<liv:titre>Caractéristiques du langage</liv:titre>
			<liv:introduction>
				<liv:paragraphe>Comme tout langage, XML a ses propres caractéristiques.</liv:paragraphe>
			</liv:introduction>
			<liv:section>
				<liv:titre>Langage ouvert</liv:titre>
				<liv:paragraphe>Repose sur son extensibilité <liv:renvoi liv:refTitre="Introduction à XML" liv:refNuméro="1">(cf. "Introduction à XML")</liv:renvoi>.</liv:paragraphe>
				<liv:paragraphe>Ensemble de balises et d'attributs quasiment non-prédéfini et peu contraint.</liv:paragraphe>
			</liv:section>
			<liv:section>
				<liv:titre>Méta-langage</liv:titre>
				<liv:paragraphe>C'est un langage. Il peut donc être "instancié" (comme un modèle).</liv:paragraphe>
				<liv:paragraphe>Ces instances peuvent être des documents (c'est l'usage courant).</liv:paragraphe>
				<liv:paragraphe>Ces instances peuvent également être d'autres langages (donc, des modèles, c'est pourquoi on qualifie XML de "méta-langage").</liv:paragraphe>
			</liv:section>
		</liv:chapitre>
		<liv:exercice liv:numéro="1">
			<liv:QCM>
				<liv:énoncé>Quelle est la nature de XML ?</liv:énoncé>
				<liv:proposition liv:numéro="1">C'est un langage structuré</liv:proposition>
				<liv:proposition liv:numéro="2">C'est un langage semi-structuré</liv:proposition>
				<liv:proposition liv:numéro="3">C'est un méta-langage</liv:proposition>
				<liv:proposition liv:numéro="4">C'est un langage totalement prédéfini</liv:proposition>
			</liv:QCM>
			<liv:corrigé>
				<liv:bonneProposition liv:numéro="2"></liv:bonneProposition>
				<liv:bonneProposition liv:numéro="3"></liv:bonneProposition>
			</liv:corrigé>
		</liv:exercice>
	</liv:leçon>
</liv:livre>
