=== BourjijKiller/XML/XSLT/guide/guide.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns="http://www.univ-amu.fr/XML/guide" xmlns:gui="http://www.univ-amu.fr/XML/guide" xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:com="http://www.univ-amu.fr/XML/commun" targetNamespace="http://www.univ-amu.fr/XML/guide" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:import namespace="http://www.univ-amu.fr/XML/commun" schemaLocation="../commun/commun.xsd"/>
	<xs:element name="guide">
		<xs:annotation>
			<xs:documentation>Guide d'itinéraires à ski</xs:documentation>
		</xs:annotation>
		<xs:complexType mixed="false">
			<xs:sequence>
				<xs:element name="titre" type="xs:string"/>
				<xs:element name="auteur" type="com:personneType" maxOccurs="unbounded"/>
				<xs:element name="éditeur" type="xs:string"/>
				<xs:element name="année" type="xs:gYear"/>
				<xs:element name="vallon" maxOccurs="unbounded">
					<xs:complexType mixed="false">
						<xs:sequence>
							<xs:element name="nom" type="xs:string"/>
							<xs:element name="introduction">
								<xs:complexType mixed="false">
									<xs:sequence>
										<xs:element ref="gui:paragraphe" maxOccurs="unbounded"/>
									</xs:sequence>
								</xs:complexType>
								<xs:unique name="noteDsIntroductionUnique">
									<xs:selector xpath=".//gui:note"/>
									<xs:field xpath="./@type"/>
									<xs:field xpath="."/>
								</xs:unique>
							</xs:element>
							<xs:element name="itinéraire" maxOccurs="unbounded">
								<xs:complexType mixed="false">
									<xs:sequence>
										<xs:element name="nom" type="xs:string"/>
										<xs:element name="altitude">
											<xs:simpleType>
												<xs:restriction base="xs:positiveInteger">
													<xs:maxExclusive value="9000"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element name="cotation">
											<xs:simpleType>
												<xs:restriction base="xs:string">
													<xs:pattern value="\*{1,5}"/>
												</xs:restriction>
											</xs:simpleType>
										</xs:element>
										<xs:element ref="gui:paragraphe" maxOccurs="unbounded"/>
									</xs:sequence>
									<xs:attribute name="numéro" use="required">
										<xs:simpleType>
											<xs:restriction base="xs:string">
												<xs:pattern value="I\d{5}"/>
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
								</xs:complexType>
								<xs:unique name="noteDsItinéraireUnique">
									<xs:selector xpath=".//gui:note"/>
									<xs:field xpath="./@type"/>
									<xs:field xpath="."/>
								</xs:unique>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
					<xs:unique name="itinéraireDsVallonUnique">
						<xs:selector xpath="./gui:itinéraire"/>
						<xs:field xpath="./gui:nom"/>
					</xs:unique>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
		<xs:unique name="vallonUnique">
			<xs:selector xpath="./gui:vallon"/>
			<xs:field xpath="./gui:nom"/>
		</xs:unique>
		<xs:unique name="itinéraireDsGuideUnique">
			<xs:selector xpath=".//gui:itinéraire"/>
			<xs:field xpath="./@numéro"/>
		</xs:unique>
		<xs:unique name="noteUnique">
			<xs:selector xpath=".//gui:note"/>
			<xs:field xpath="./@id"/>
		</xs:unique>
		<xs:key name="ItinéraireNoteKey">
			<xs:selector xpath=".//gui:itinéraire | .//gui:note"/>
			<xs:field xpath="./@numéro | ./@id"/>
		</xs:key>
		<xs:keyref name="renvoiKeyref" refer="gui:ItinéraireNoteKey">
			<xs:selector xpath=".//gui:renvoi"/>
			<xs:field xpath="./@ref"/>
		</xs:keyref>
	</xs:element>
	<xs:element name="paragraphe">
		<xs:complexType mixed="true">
			<xs:choice minOccurs="0" maxOccurs="unbounded">
				<xs:element name="renvoi">
					<xs:complexType mixed="false">
						<xs:attribute name="ref" use="required">
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:pattern value="N\d{5}"/>
									<xs:pattern value="I\d{5}"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
					</xs:complexType>
				</xs:element>
				<xs:element name="note">
					<xs:complexType>
						<xs:simpleContent>
							<xs:extension base="xs:string">
								<xs:attribute name="type" use="required">
									<xs:simpleType>
										<xs:restriction base="xs:string">
											<xs:enumeration value="prudence"/>
											<xs:enumeration value="matériel"/>
										</xs:restriction>
									</xs:simpleType>
								</xs:attribute>
								<xs:attribute name="id">
									<xs:simpleType>
										<xs:restriction base="xs:string">
											<xs:pattern value="N\d{5}"/>
										</xs:restriction>
									</xs:simpleType>
								</xs:attribute>
							</xs:extension>
						</xs:simpleContent>
					</xs:complexType>
				</xs:element>
			</xs:choice>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== BourjijKiller/XML/XSLT/guide/guide.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="guide.xsl" type="text/xsl"?>
<gui:guide xsi:schemaLocation="http://www.univ-amu.fr/XML/guide guide.xsd"
			xmlns:gui="http://www.univ-amu.fr/XML/guide"
			xmlns:com="http://www.univ-amu.fr/XML/commun"
			xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<gui:titre>Itinéraire skieurs de la Vallée de la Clarée</gui:titre>
	<gui:auteur>
		<com:civilité>M.</com:civilité>
		<com:prénomUsuel>Jean-Gabriel</com:prénomUsuel>
		<com:nom>Ravary</com:nom>
	</gui:auteur>
	<gui:éditeur>Le Polygraphe</gui:éditeur>
	<gui:année>1991</gui:année>
	<gui:vallon>
		<gui:nom>Vallon des Muandes</gui:nom>
		<gui:introduction>
			<gui:paragraphe>Vallon situé à l'EST du refuge des Drayères.</gui:paragraphe>
			<gui:paragraphe>Le vallon le plus utilisé pour la traversé de la Vallée Etroite. Ce vallon est également accessible du refuge Laval</gui:paragraphe>
		</gui:introduction>
		<gui:itinéraire numéro="I00001">
			<gui:nom>Col de Névache</gui:nom>
			<gui:altitude>2794</gui:altitude>
			<gui:cotation>**</gui:cotation>
			<gui:paragraphe>S'élever au-dessus du refuge des Drayères en direction Est. Suivre la rive droite du torrent de Brune puis s'engager sur le flanc droit du ravin des Muandes que l'on quitte vers 2500 m pour rejoindre le col situé au Nord. Descente possible sur Valmeinier. <gui:note type="prudence" id="N00001">Départ assez raide</gui:note></gui:paragraphe>
		</gui:itinéraire>
		<gui:itinéraire numéro="I00002">
			<gui:nom>Pointe de Névache</gui:nom>
			<gui:altitude>2892</gui:altitude>
			<gui:cotation>***</gui:cotation>
			<gui:paragraphe>Du Col de Névache (itinéraire n°1) <gui:renvoi ref="I00001"/>, suivre la ligne de crête qui mène à la Pointe de Névache. <gui:note type="prudence" id="N00002">Attention : corniches possibles.</gui:note> <gui:note type="matériel" id="N00003">Crampons utiles au printemps.</gui:note></gui:paragraphe>
		</gui:itinéraire>
	</gui:vallon>
	<gui:vallon>
		<gui:nom>Vallons de Thyon - Les Collons</gui:nom>
		<gui:introduction>
			<gui:paragraphe>Cet ensemble de 4 vallons est situé dans les Alpes Suisses.</gui:paragraphe>
		</gui:introduction>
		<gui:itinéraire numéro="I00003">
			<gui:nom>Raquettes au clair de lune</gui:nom>
			<gui:altitude>2357</gui:altitude>
			<gui:cotation>*</gui:cotation>
			<gui:paragraphe>Notre équipe de guides vous propose des randonnées en raquettes au clair de lune durant toute la période hivernale ainsi que pendant la période estivale <gui:renvoi ref="I00001"/>. <gui:note id="N00004" type="matériel">Vous devez venir avec vos propres raquettes ou en avoir loué avant le départ de la randonnée.</gui:note></gui:paragraphe>
		</gui:itinéraire>
	</gui:vallon>
</gui:guide>
