=== BourjijKiller/XML/DTD/commun/commun.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!-- ENTITY PARAMETRE PERSONNE -->
<!ENTITY % personne "civilite, prenom-usuel, prenom-complementaire*, nom">
<!-- ENTITY PARAMETRE COORDREDUITE -->
<!ENTITY % coordReduite "coordonnees">
<!-- ENTITY ADRESSE POSTALE -->
<!ENTITY % adressePostale "adresse-postale">

<!-- DESCRIPTION D'UNE PERSONNE-->
<!ELEMENT civilite EMPTY>
<!ATTLIST civilite type (M.|Mme|Mlle) #REQUIRED>
<!ELEMENT prenom-usuel (#PCDATA)>
<!ELEMENT prenom-complementaire (#PCDATA)>
<!ELEMENT nom (#PCDATA)>

<!-- COORDONNEES D'UNE PERSONNE REDUITE OU COMPLETE -->
<!ELEMENT coordonnees (complete | reduite)*>

<!ELEMENT reduite (identite, num-tel, num-fax?, email?)>
<!ELEMENT complete (identite, adresse-postale, num-tel+, num-fax*, email*)>

<!ELEMENT adresse-postale (precision-personnelle?, complement-geo?, voie, service-postale?, localite, pays?)>
<!ELEMENT precision-personnelle (#PCDATA)>
<!ELEMENT complement-geo (#PCDATA)>

<!-- ELEMENT VOIE -->
<!ELEMENT voie (numero-voie?, type-voie?, nom-voie)>
<!ELEMENT numero-voie (#PCDATA)>
<!ELEMENT type-voie (#PCDATA)>
<!ELEMENT nom-voie (#PCDATA)>

<!ELEMENT service-postale (#PCDATA)>

<!-- ELEMENT localite -->
<!ELEMENT localite (code-postal, nom-commune, CEDEX?)>
<!ELEMENT code-postal (#PCDATA)>
<!ELEMENT nom-commune (#PCDATA)>
<!ELEMENT CEDEX (#PCDATA)>
<!ATTLIST CEDEX value CDATA #REQUIRED>

<!ELEMENT pays (#PCDATA)>

<!ELEMENT num-tel (#PCDATA)>
<!ELEMENT num-fax (#PCDATA)>

<!ELEMENT email (#PCDATA)>

<!-- IDENTITE -->
<!ELEMENT identite (denomination | raison-sociale | appelation)>

<!-- DENOMINATION D'UNE PERSONNE -->
<!ELEMENT denomination (%personne;)>
<!ELEMENT raison-sociale (#PCDATA)>
<!ELEMENT appelation (#PCDATA)>

=== BourjijKiller/XML/DTD/commun/adressePostale.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE adresse-postale SYSTEM "commun.dtd" >
<adresse-postale>
  <precision-personnelle>
  	Appartement 558
  </precision-personnelle>
  <voie>
    <numero-voie>56</numero-voie>
    <type-voie>avenue</type-voie>
    <nom-voie>Doriane Boolosse</nom-voie>
  </voie>
  <localite>
    <code-postal>13256</code-postal>
    <nom-commune>Aix-en-Provence</nom-commune>
    <CEDEX value="8"></CEDEX>
  </localite>
  <pays>FRANCE</pays>
</adresse-postale>

=== BourjijKiller/XML/DTD/commun/coordonnéesComplètes.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE complete SYSTEM "commun.dtd" >
<complete>
  <identite>
    <denomination>
      <civilite type="M."/>
      <prenom-usuel>
      	Samuel
      </prenom-usuel>
      <nom>
      	Entezam
      </nom>
    </denomination>
  </identite>
  <adresse-postale>
  <precision-personnelle>
  	Appartement 558
  </precision-personnelle>
  <voie>
    <numero-voie>56</numero-voie>
    <type-voie>avenue</type-voie>
    <nom-voie>Doriane Boolosse</nom-voie>
  </voie>
  <localite>
    <code-postal>13256</code-postal>
    <nom-commune>Aix-en-Provence</nom-commune>
    <CEDEX value="8"></CEDEX>
  </localite>
  <pays>FRANCE</pays>
</adresse-postale>
  <num-tel>
  	04.35.45.78.96
  </num-tel>
  <num-tel>
  	04.87.65.23.78
  </num-tel>
  <num-fax>
  	02.58.45.65.32
  </num-fax>
  <email>
  	sami1606@live.fr
  </email>
</complete>
