=== BourjijKiller/XML/PHP_XML/SimpleXML/Catalogue/catalogue.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- édité avec XMLSpy v2018 (x64) (http://www.altova.com) par Philippe RAMADOUR (MIAGE Marseille) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:cat="http://www.univ-amu.fr/XML/catalogue" targetNamespace="http://www.univ-amu.fr/XML/catalogue" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="catalogue">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="famille" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="nom" type="xs:string"/>
							<xs:element name="produit" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="désignation" type="xs:string"/>
										<xs:element name="quantitéStock" type="xs:positiveInteger"/>
										<xs:element name="prix">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="montant">
														<xs:simpleType>
															<xs:restriction base="xs:string">
																<xs:pattern value="\d*\.\d{2}"/>
															</xs:restriction>
														</xs:simpleType>
													</xs:element>
												</xs:sequence>
												<xs:attribute name="devise">
													<xs:simpleType>
														<xs:restriction base="xs:string">
															<xs:enumeration value="EURO"/>
															<xs:enumeration value="DOLLAR US"/>
															<xs:enumeration value="LIVRE"/>
														</xs:restriction>
													</xs:simpleType>
												</xs:attribute>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
									<xs:attribute name="référence">
										<xs:simpleType>
											<xs:restriction base="xs:string">
												<xs:pattern value="[A-Z]{2}-[A-Z]{3,4}-\d{4}"/>
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== BourjijKiller/XML/PHP_XML/DOM/TP_PHP/xml/CatalogueXML/catalogue.xml
<?xml version="1.0" encoding="UTF-8"?><cat:catalogue xmlns:cat="http://www.univ-amu.fr/XML/catalogue"			   xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"			   xsi:schemaLocation="http://www.univ-amu.fr/XML/catalogue catalogue.xsd">	<cat:famille>		<cat:nom>Produits techniques</cat:nom>		<cat:produit référence="PT-LCD-2587">			<cat:désignation>Ecran LCD 20" SYNO</cat:désignation>			<cat:quantitéStock>15</cat:quantitéStock>			<cat:prix devise="EURO"><cat:montant>899.00</cat:montant></cat:prix>		</cat:produit>		<cat:produit référence="PT-PORT-4896">			<cat:désignation>Téléphone Portable RZR-X300</cat:désignation>			<cat:quantitéStock>50</cat:quantitéStock>			<cat:prix devise="DOLLAR US"><cat:montant>499.00</cat:montant></cat:prix>		</cat:produit>		<!-- ... Autres produits de la même famille ... -->	</cat:famille>	<cat:famille>		<cat:nom>Gros électro-ménager</cat:nom>		<cat:produit référence="SM-DEGI-7802">			<cat:désignation>Réfrigirateur F7802 SAMSUNG</cat:désignation>			<cat:quantitéStock>2</cat:quantitéStock>			<cat:prix devise="EURO">				<cat:montant>999.00</cat:montant>			</cat:prix>		</cat:produit>		<cat:produit référence="LG-AMER-5500">			<cat:désignation>Refrigirateur américain LG 5500</cat:désignation>			<cat:quantitéStock>3</cat:quantitéStock>			<cat:prix devise="EURO">				<cat:montant>1099.00</cat:montant>			</cat:prix>		</cat:produit>		<!-- ... Autres produits de la même famille ... -->	</cat:famille>	<!-- ... Autres familles de produits ... --></cat:catalogue>
