=== BourjijKiller/XML/XPath/dictionnaire/dictionnaire.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:dico="http://www.univ-amu.fr/XML/dictionnaire" targetNamespace="http://www.univ-amu.fr/XML/dictionnaire" elementFormDefault="qualified" attributeFormDefault="qualified">
	<xs:element name="dictionnaire">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="entrée" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="orthographe">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="usuelle" type="xs:string"/>
										<xs:element name="dérivée" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:choice>
								<xs:element name="nomPropre">
									<xs:complexType mixed="false"/>
								</xs:element>
								<xs:element name="nomCommun" type="dico:nomCommunAdjectifType"/>
								<xs:element name="adjectif" type="dico:nomCommunAdjectifType"/>
								<xs:element name="verbe">
									<xs:complexType>
										<xs:sequence>
											<xs:element name="groupe">
												<xs:complexType>
													<xs:sequence>
														<xs:element ref="dico:annotation" minOccurs="0" maxOccurs="unbounded"/>
													</xs:sequence>
													<xs:attribute name="valeur" use="required">
														<xs:simpleType>
															<xs:restriction base="xs:string">
																<xs:enumeration value="1er"/>
																<xs:enumeration value="2ème"/>
																<xs:enumeration value="3ème"/>
															</xs:restriction>
														</xs:simpleType>
													</xs:attribute>
												</xs:complexType>
												<xs:unique name="annotationDsGroupeUnique">
													<xs:selector xpath="./dico:annotation"/>
													<xs:field xpath="."/>
												</xs:unique>
											</xs:element>
											<xs:element name="forme">
												<xs:complexType>
													<xs:sequence>
														<xs:element ref="dico:annotation" minOccurs="0" maxOccurs="unbounded"/>
													</xs:sequence>
													<xs:attribute name="valeur" use="required">
														<xs:simpleType>
															<xs:restriction base="xs:string">
																<xs:enumeration value="transitif"/>
																<xs:enumeration value="intransitif"/>
																<xs:enumeration value="réfléchi"/>
															</xs:restriction>
														</xs:simpleType>
													</xs:attribute>
												</xs:complexType>
												<xs:unique name="annotationDsFormeUnique">
													<xs:selector xpath="./dico:annotation"/>
													<xs:field xpath="."/>
												</xs:unique>
											</xs:element>
										</xs:sequence>
									</xs:complexType>
								</xs:element>
								<xs:element name="pronomPersonnel">
									<xs:complexType mixed="false"/>
								</xs:element>
								<xs:element name="pronomRelatif">
									<xs:complexType mixed="false"/>
								</xs:element>
							</xs:choice>
							<xs:element ref="dico:prononciation"/>
							<xs:choice>
								<xs:element ref="dico:renvoi"/>
								<xs:element name="signification" maxOccurs="unbounded">
									<xs:complexType>
										<xs:sequence>
											<xs:element ref="dico:domaine"/>
											<xs:element ref="dico:sens"/>
											<xs:element ref="dico:exemple" minOccurs="0" maxOccurs="unbounded"/>
											<xs:element ref="dico:traduction" minOccurs="0" maxOccurs="unbounded"/>
										</xs:sequence>
									</xs:complexType>
									<xs:unique name="exempleDsSignificationUnique">
										<xs:selector xpath="./dico:exemple"/>
										<xs:field xpath="."/>
									</xs:unique>
									<xs:unique name="traductionDsSignificationUnique">
										<xs:selector xpath="./dico:traduction"/>
										<xs:field xpath="./dico:langue"/>
										<xs:field xpath="./dico:écriture"/>
									</xs:unique>
								</xs:element>
							</xs:choice>
							<xs:element name="expression" minOccurs="0" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="écriture" type="xs:string"/>
										<xs:element ref="dico:domaine"/>
										<xs:element ref="dico:sens"/>
										<xs:element ref="dico:exemple" minOccurs="0" maxOccurs="unbounded"/>
										<xs:element ref="dico:traduction" minOccurs="0" maxOccurs="unbounded"/>
									</xs:sequence>
								</xs:complexType>
								<xs:unique name="exempleDsExpressionUnique">
									<xs:selector xpath="./dico:exemple"/>
									<xs:field xpath="."/>
								</xs:unique>
								<xs:unique name="traductionDsExpressionUnique">
									<xs:selector xpath="./dico:traduction"/>
									<xs:field xpath="./dico:langue"/>
									<xs:field xpath="./dico:écriture"/>
								</xs:unique>
							</xs:element>
							<xs:element name="étymologie" type="xs:string" minOccurs="0"/>
						</xs:sequence>
					</xs:complexType>
					<xs:unique name="orthographeUnique">
						<xs:selector xpath=".//dico:orthographe/dico:*"/>
						<xs:field xpath="."/>
					</xs:unique>
					<xs:unique name="expressionUnique">
						<xs:selector xpath="./dico:expression"/>
						<xs:field xpath="./dico:écriture"/>
					</xs:unique>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
		<xs:key name="entréeKey">
			<xs:selector xpath="./dico:entrée"/>
			<xs:field xpath=".//dico:usuelle"/>
		</xs:key>
		<xs:keyref name="renvoiKeyref" refer="dico:entréeKey">
			<xs:selector xpath=".//dico:renvoi"/>
			<xs:field xpath="."/>
		</xs:keyref>
	</xs:element>
	<xs:complexType name="nomCommunAdjectifType">
		<xs:sequence>
			<xs:element name="genre">
				<xs:complexType>
					<xs:sequence>
						<xs:element ref="dico:annotation" minOccurs="0" maxOccurs="unbounded"/>
					</xs:sequence>
					<xs:attribute name="valeur" use="required">
						<xs:simpleType>
							<xs:restriction base="xs:string">
								<xs:enumeration value="masculin"/>
								<xs:enumeration value="féminin"/>
								<xs:enumeration value="neutre"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
				</xs:complexType>
				<xs:unique name="annotationDsGenreUnique">
					<xs:selector xpath="./dico:annotation"/>
					<xs:field xpath="."/>
				</xs:unique>
			</xs:element>
			<xs:element name="nombre">
				<xs:complexType>
					<xs:sequence>
						<xs:element ref="dico:annotation" minOccurs="0" maxOccurs="unbounded"/>
					</xs:sequence>
					<xs:attribute name="valeur" use="required">
						<xs:simpleType>
							<xs:restriction base="xs:string">
								<xs:enumeration value="singulier"/>
								<xs:enumeration value="pluriel"/>
							</xs:restriction>
						</xs:simpleType>
					</xs:attribute>
				</xs:complexType>
				<xs:unique name="annotationDsNombreUnique">
					<xs:selector xpath="./dico:annotation"/>
					<xs:field xpath="."/>
				</xs:unique>
			</xs:element>
		</xs:sequence>
	</xs:complexType>
	<xs:element name="annotation" type="xs:string"/>
	<xs:element name="renvoi" type="xs:string"/>
	<xs:element name="prononciation" type="xs:string"/>
	<xs:element name="domaine">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="langage familier"/>
				<xs:enumeration value="langage courant"/>
				<xs:enumeration value="finance"/>
				<xs:enumeration value="informatique"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="sens">
		<xs:complexType mixed="true">
			<xs:sequence>
				<xs:element ref="dico:renvoi" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
		<xs:unique name="renvoiUnique">
			<xs:selector xpath="./dico:renvoi"/>
			<xs:field xpath="."/>
		</xs:unique>
	</xs:element>
	<xs:element name="exemple" type="xs:string"/>
	<xs:element name="traduction">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="langue">
					<xs:simpleType>
						<xs:restriction base="xs:string">
							<xs:enumeration value="anglais"/>
							<xs:enumeration value="américain"/>
							<xs:enumeration value="espagnol"/>
							<xs:enumeration value="italien"/>
						</xs:restriction>
					</xs:simpleType>
				</xs:element>
				<xs:element name="écriture" type="xs:string"/>
				<xs:element ref="dico:prononciation"/>
				<xs:element ref="dico:annotation" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
		<xs:unique name="annotationDsTraductionUnique">
			<xs:selector xpath="./dico:annotation"/>
			<xs:field xpath="."/>
		</xs:unique>
	</xs:element>
</xs:schema>

=== BourjijKiller/XML/XPath/dictionnaire/dictionnaire.xml
<?xml version="1.0" encoding="UTF-8"?>
<dico:dictionnaire xmlns:dico="http://www.univ-amu.fr/XML/dictionnaire" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.univ-amu.fr/XML/dictionnaire dictionnaire.xsd">
	<dico:entrée>
		<dico:orthographe>
			<dico:usuelle>oignon</dico:usuelle>
			<dico:dérivée>ognon</dico:dérivée>
			<dico:dérivée>onion</dico:dérivée>
		</dico:orthographe>
		<dico:nomCommun>
			<dico:genre dico:valeur="masculin"/>
			<dico:nombre dico:valeur="singulier"/>
		</dico:nomCommun>
		<dico:prononciation>oanion</dico:prononciation>
		<dico:signification>
			<dico:domaine>langage courant</dico:domaine>
			<dico:sens>Plante (liliacée) potagère du genre ail, dont le bulbe, d'une saveur et d'une odeur fortes et piquantes, est très employé en cuisine ; le bulbe lui-même. (L'oignon est une plante bisannuelle bulbeuse très anciennement cultivée.)</dico:sens>
			<dico:traduction>
				<dico:langue>espagnol</dico:langue>
				<dico:écriture>cebola</dico:écriture>
				<dico:prononciation>sébola</dico:prononciation>
			</dico:traduction>
		</dico:signification>
		<dico:expression>
			<dico:écriture>C'est pas tes oignons</dico:écriture>
			<dico:domaine>langage courant</dico:domaine>
			<dico:sens>Ce ne sont pas tes affaires, ça ne te concerne pas.</dico:sens>
			<dico:exemple>Mêle toi de tes affaires : ce ne sont pas tes oignons, ça ne regarde que moi !</dico:exemple>
		</dico:expression>
	</dico:entrée>
	<dico:entrée>
		<dico:orthographe>
			<dico:usuelle>cuisiner</dico:usuelle>
		</dico:orthographe>
		<dico:verbe>
			<dico:groupe dico:valeur="1er"></dico:groupe>
			<dico:forme dico:valeur="transitif"></dico:forme>
		</dico:verbe>
		<dico:prononciation>cuiziné</dico:prononciation>
		<dico:signification>
			<dico:domaine>langage courant</dico:domaine>
			<dico:sens>Préparer et accommoder les aliments de telle sorte qu'ils soient propres à la consommation et agréables au goût</dico:sens>
		</dico:signification>
		<dico:expression>
			<dico:écriture>Cuisiner quelqu'un</dico:écriture>
			<dico:domaine>langage familier</dico:domaine>
			<dico:sens>Interroger quelqu'un</dico:sens>
		</dico:expression>
	</dico:entrée>
	<dico:entrée>
		<dico:orthographe>
			<dico:usuelle>préparer</dico:usuelle>
		</dico:orthographe>
		<dico:verbe>
			<dico:groupe dico:valeur="1er"></dico:groupe>
			<dico:forme dico:valeur="transitif"></dico:forme>
		</dico:verbe>
		<dico:prononciation>préparé</dico:prononciation>
		<dico:signification>
			<dico:domaine>langage courant</dico:domaine>
			<dico:sens>Choisir, prendre, disposer à l'avance ce qui sera nécessaire pour une opération quelconque</dico:sens>
		</dico:signification>
		<dico:expression>
			<dico:écriture>Préparer le repas</dico:écriture>
			<dico:domaine>langage courant</dico:domaine>
			<dico:sens><dico:renvoi>cuisiner</dico:renvoi></dico:sens>
		</dico:expression>
	</dico:entrée>
</dico:dictionnaire>

<!-- 
Expressions XPath :
	- Vers quel(s) mot(s) le 3ème mot du dictionnaire possède-t-il des renvois (retourner la chaîne de caractères représentant l’orthographe usuelle des mots répondant à la question) ?.//dico:entrée[3]//dico:renvoi/text()
	- Quelle est la liste des mots possédant plusieurs définitions et dont l’une d’entre elles au moins relève du domaine de l'informatique (retourner les éléments correspondant aux mots répondant à la question) ? .//dico:entrée[count(.//dico:signification) > 1][.//dico:signification/dico:domaine/text() = "informatique"]
	- Quelle est la liste des mots possédant une traduction espagnole dans au moins une de leurs définitions (retourner la chaîne de caractères représentant l’orthographe usuelle des mots répondant à la question) ? .//dico:entrée[.//dico:signification//dico:langue = "espagnol"]/dico:orthographe/dico:usuelle/text()
	- Quelle est la liste des mots possédant une note concernant leur pluriel (i.e. dont le nombre contient une annotation contenant elle-même la chaîne "pluriel" ; retourner la chaîne de caractères représentant l’orthographe usuelle des mots répondant à la question) ? .//dico:entrée[.//dico:nombre/dico:annotation[contains(./text(), "pluriel")]]/dico:orthographe/dico:usuelle/text()
	- Existe-t-il un ou plusieurs mots possédant plus de 5 traductions dans l'entrée correspondante (6 ou plus : retourner un booléen) ? boolean(.//dico:entrée[count(.//dico:traduction) > 5])
	- Quelle est la liste des traductions italiennes figurant dans le dictionnaire (retourner les éléments correspondant aux traductions répondant à la question) ? .//dico:traduction[./dico:langue = "italien"]
	- Quelle est la liste des mots ne possédant pas dans leur entrée de traduction ni d’étymologie (retourner les éléments correspondant aux mots répondant à la question) ? .//dico:entrée[not(.//dico:traduction) and not(.//dico:étymologie)]
	- Quelle est la liste des homonymes ("homonyme" se dit d’un mot qui se prononce (homophone) ou s’écrit (homographe) de la même manière qu’un autre mais n’a pas le même sens ; retourner les éléments correspondant aux mots répondant à la question) ?
		(Recherche des homophones : .//dico:entrée[(./dico:prononciation = ./preceding-sibling::dico:entrée/dico:prononciation) or (./dico:prononciation = ./following-sibling::dico:entrée/dico:prononciation)])
		(Recherche des homographes : .//dico:entrée[count(./dico:significationEntrée) > 1])
		(Donc, pour le tout, on a : .//dico:entrée[(./dico:prononciation = ./preceding-sibling::dico:entrée/dico:prononciation) or (./dico:prononciation = ./following-sibling::dico:entrée/dico:prononciation)])|(.//dico:entrée[count(./dico:significationEntrée) > 1])
	- Quelle est la liste des mots liés à un autre mot qui est lui-même lié à eux (existence de cycles à 2 nœuds dans le graphe des liens hypertextes du dictionnaire ; retourner la chaîne de caractères représentant l’orthographe usuelle des mots répondant à la question) ? IMPOSSIBLE AVEC XPATH 1.0
 -->
