=== BourjijKiller/XML/PHP_XML/SimpleXML/MIAGE/MIAGE.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- édité avec XMLSpy v2017 rel. 3 (x64) (http://www.altova.com) par Philippe Ramadour (MIAGE Marseille) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" xmlns:miage="http://www.univ-amu.fr/XML/MIAGE" targetNamespace="http://www.univ-amu.fr/XML/MIAGE" elementFormDefault="qualified" attributeFormDefault="unqualified">
	<xs:element name="MIAGE">
		<xs:annotation>
			<xs:documentation>Descriptif des formations de l'IUP MIAGE d'Aix-Marseille en 2005/2006</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:sequence>
				<xs:element name="formation" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="intitulé" type="xs:string"/>
							<xs:element name="semestre" minOccurs="2" maxOccurs="2">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="UE" maxOccurs="unbounded">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="intitulé" type="xs:string"/>
													<xs:element name="ECTS">
														<xs:simpleType>
															<xs:restriction base="xs:positiveInteger">
																<xs:minInclusive value="1"/>
																<xs:maxInclusive value="60"/>
															</xs:restriction>
														</xs:simpleType>
													</xs:element>
													<xs:element name="module" maxOccurs="unbounded">
														<xs:complexType>
															<xs:sequence>
																<xs:element name="intitulé" type="xs:string"/>
																<xs:element name="heures">
																	<xs:complexType>
																		<xs:sequence>
																			<xs:element name="CM" type="xs:nonNegativeInteger"/>
																			<xs:element name="TDTP" type="xs:nonNegativeInteger"/>
																		</xs:sequence>
																	</xs:complexType>
																</xs:element>
															</xs:sequence>
														</xs:complexType>
													</xs:element>
												</xs:sequence>
												<xs:attribute name="type">
													<xs:simpleType>
														<xs:restriction base="xs:string">
															<xs:enumeration value="obligatoire"/>
															<xs:enumeration value="optionnelle"/>
														</xs:restriction>
													</xs:simpleType>
												</xs:attribute>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
									<xs:attribute name="numéro">
										<xs:simpleType>
											<xs:restriction base="xs:string">
												<xs:enumeration value="S1"/>
												<xs:enumeration value="S2"/>
											</xs:restriction>
										</xs:simpleType>
									</xs:attribute>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
						<xs:attribute name="niveau">
							<xs:simpleType>
								<xs:restriction base="xs:string">
									<xs:enumeration value="L3"/>
									<xs:enumeration value="M1"/>
									<xs:enumeration value="M2"/>
								</xs:restriction>
							</xs:simpleType>
						</xs:attribute>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== BourjijKiller/XML/PHP_XML/DOM/TP_PHP/xml/MIAGEXML/MIAGE.xml
<?xml version="1.0" encoding="UTF-8"?>
<miage:MIAGE xmlns:miage="http://www.univ-amu.fr/XML/MIAGE" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.univ-amu.fr/XML/MIAGE ./MIAGE.xsd">
	<miage:formation niveau="L3">
		<miage:intitulé>Licence Mathématiques-Informatique parcours MIAGE</miage:intitulé>
		<miage:semestre numéro="S1">
			<miage:UE type="obligatoire">
				<miage:intitulé>Théorie des organisations et Marketing</miage:intitulé>
				<miage:ECTS>6</miage:ECTS>
				<miage:module>
					<miage:intitulé>Théorie des organisations et nouvelles technologies</miage:intitulé>
					<miage:heures>
						<miage:CM>15</miage:CM>
						<miage:TDTP>15</miage:TDTP>
					</miage:heures>
				</miage:module>
				<miage:module>
					<miage:intitulé>Marketing commercial</miage:intitulé>
					<miage:heures>
						<miage:CM>20</miage:CM>
						<miage:TDTP>10</miage:TDTP>
					</miage:heures>
				</miage:module>
			</miage:UE>
			<miage:UE type="obligatoire">
				<miage:intitulé>Outils d'aide à la décision</miage:intitulé>
				<miage:ECTS>6</miage:ECTS>
				<miage:module>
					<miage:intitulé>Recherche opérationnelle</miage:intitulé>
					<miage:heures>
						<miage:CM>15</miage:CM>
						<miage:TDTP>15</miage:TDTP>
					</miage:heures>
				</miage:module>
				<miage:module>
					<miage:intitulé>Statistique et analyse de données</miage:intitulé>
					<miage:heures>
						<miage:CM>15</miage:CM>
						<miage:TDTP>15</miage:TDTP>
					</miage:heures>
				</miage:module>
			</miage:UE>
			<miage:UE type="obligatoire">
				<miage:intitulé>Informatique 1</miage:intitulé>
				<miage:ECTS>6</miage:ECTS>
				<miage:module>
					<miage:intitulé>Programmation événementielle / VB</miage:intitulé>
					<miage:heures>
						<miage:CM>20</miage:CM>
						<miage:TDTP>40</miage:TDTP>
					</miage:heures>
				</miage:module>
			</miage:UE>
			<miage:UE type="obligatoire">
				<miage:intitulé>Informatique 2</miage:intitulé>
				<miage:ECTS>6</miage:ECTS>
				<miage:module>
					<miage:intitulé>Algorithmique</miage:intitulé>
					<miage:heures>
						<miage:CM>20</miage:CM>
						<miage:TDTP>40</miage:TDTP>
					</miage:heures>
				</miage:module>
			</miage:UE>
			<miage:UE type="obligatoire">
				<miage:intitulé>Projet</miage:intitulé>
				<miage:ECTS>6</miage:ECTS>
				<miage:module>
					<miage:intitulé>Gestion de projets</miage:intitulé>
					<miage:heures>
						<miage:CM>15</miage:CM>
						<miage:TDTP>15</miage:TDTP>
					</miage:heures>
				</miage:module>
				<miage:module>
					<miage:intitulé>Projet</miage:intitulé>
					<miage:heures>
						<miage:CM>0</miage:CM>
						<miage:TDTP>30</miage:TDTP>
					</miage:heures>
				</miage:module>
			</miage:UE>
		</miage:semestre>
		<miage:semestre numéro="S2">
			<miage:UE type="obligatoire">
				<miage:intitulé>Systèmes d'information</miage:intitulé>
				<miage:ECTS>6</miage:ECTS>
				<miage:module>
					<miage:intitulé>Conception de systèmes d'information</miage:intitulé>
					<miage:heures>
						<miage:CM>30</miage:CM>
						<miage:TDTP>30</miage:TDTP>
					</miage:heures>
				</miage:module>
			</miage:UE>
			<miage:UE type="obligatoire">
				<miage:intitulé>Informatique 3</miage:intitulé>
				<miage:ECTS>6</miage:ECTS>
				<miage:module>
					<miage:intitulé>Bases de données</miage:intitulé>
					<miage:heures>
						<miage:CM>20</miage:CM>
						<miage:TDTP>40</miage:TDTP>
					</miage:heures>
				</miage:module>
			</miage:UE>
			<miage:UE type="obligatoire">
				<miage:intitulé>Informatique 4</miage:intitulé>
				<miage:ECTS>6</miage:ECTS>
				<miage:module>
					<miage:intitulé>Programmation objet / Génie logiciel</miage:intitulé>
					<miage:heures>
						<miage:CM>20</miage:CM>
						<miage:TDTP>40</miage:TDTP>
					</miage:heures>
				</miage:module>
			</miage:UE>
			<miage:UE type="obligatoire">
				<miage:intitulé>Langue et Projet</miage:intitulé>
				<miage:ECTS>6</miage:ECTS>
				<miage:module>
					<miage:intitulé>Anglais</miage:intitulé>
					<miage:heures>
						<miage:CM>0</miage:CM>
						<miage:TDTP>30</miage:TDTP>
					</miage:heures>
				</miage:module>
				<miage:module>
					<miage:intitulé>Soutenance et mémoire de projet</miage:intitulé>
					<miage:heures>
						<miage:CM>0</miage:CM>
						<miage:TDTP>30</miage:TDTP>
					</miage:heures>
				</miage:module>
			</miage:UE>
			<miage:UE type="obligatoire">
				<miage:intitulé>Stage</miage:intitulé>
				<miage:ECTS>6</miage:ECTS>
				<miage:module>
					<miage:intitulé>Stage</miage:intitulé>
					<miage:heures>
						<miage:CM>0</miage:CM>
						<miage:TDTP>0</miage:TDTP>
					</miage:heures>
				</miage:module>
			</miage:UE>
		</miage:semestre>
	</miage:formation>
	<miage:formation niveau="L3">
		<miage:intitulé>Licence de Gestion parcours MIAGE</miage:intitulé>
		<miage:semestre numéro="S1">
			<miage:UE type="obligatoire">
				<miage:intitulé>Comptabilité et Droit</miage:intitulé>
				<miage:ECTS>6</miage:ECTS>
				<miage:module>
					<miage:intitulé>Comptabilité des sociétés</miage:intitulé>
					<miage:heures>
						<miage:CM>30</miage:CM>
						<miage:TDTP>16</miage:TDTP>
					</miage:heures>
				</miage:module>
				<miage:module>
					<miage:intitulé>Droit commercial</miage:intitulé>
					<miage:heures>
						<miage:CM>20</miage:CM>
						<miage:TDTP>0</miage:TDTP>
					</miage:heures>
				</miage:module>
			</miage:UE>
			<miage:UE type="obligatoire">
				<miage:intitulé>Marketing</miage:intitulé>
				<miage:ECTS>9</miage:ECTS>
				<miage:module>
					<miage:intitulé>Marketing commercial</miage:intitulé>
					<miage:heures>
						<miage:CM>20</miage:CM>
						<miage:TDTP>10</miage:TDTP>
					</miage:heures>
				</miage:module>
				<miage:module>
					<miage:intitulé>Etudes de marché</miage:intitulé>
					<miage:heures>
						<miage:CM>20</miage:CM>
						<miage:TDTP>10</miage:TDTP>
					</miage:heures>
				</miage:module>
			</miage:UE>
			<miage:UE type="obligatoire">
				<miage:intitulé>Informatique et Langue</miage:intitulé>
				<miage:ECTS>6</miage:ECTS>
				<miage:module>
					<miage:intitulé>Informatique niveau 5 (BD)</miage:intitulé>
					<miage:heures>
						<miage:CM>0</miage:CM>
						<miage:TDTP>30</miage:TDTP>
					</miage:heures>
				</miage:module>
				<miage:module>
					<miage:intitulé>Anglais</miage:intitulé>
					<miage:heures>
						<miage:CM>0</miage:CM>
						<miage:TDTP>30</miage:TDTP>
					</miage:heures>
				</miage:module>
			</miage:UE>
			<miage:UE type="obligatoire">
				<miage:intitulé>Options</miage:intitulé>
				<miage:ECTS>3</miage:ECTS>
				<miage:module>
					<miage:intitulé>Gestion des ressources humaines ou Sport</miage:intitulé>
					<miage:heures>
						<miage:CM>20</miage:CM>
						<miage:TDTP>10</miage:TDTP>
					</miage:heures>
				</miage:module>
			</miage:UE>
			<miage:UE type="obligatoire">
				<miage:intitulé>MIAGE 1</miage:intitulé>
				<miage:ECTS>3</miage:ECTS>
				<miage:module>
					<miage:intitulé>Algorithmique et programmation</miage:intitulé>
					<miage:heures>
						<miage:CM>30</miage:CM>
						<miage:TDTP>20</miage:TDTP>
					</miage:heures>
				</miage:module>
			</miage:UE>
			<miage:UE type="obligatoire">
				<miage:intitulé>MIAGE 2</miage:intitulé>
				<miage:ECTS>3</miage:ECTS>
				<miage:module>
					<miage:intitulé>Gestion de projets</miage:intitulé>
					<miage:heures>
						<miage:CM>15</miage:CM>
						<miage:TDTP>15</miage:TDTP>
					</miage:heures>
				</miage:module>
				<miage:module>
					<miage:intitulé>Programmation orientée objets</miage:intitulé>
					<miage:heures>
						<miage:CM>15</miage:CM>
						<miage:TDTP>10</miage:TDTP>
					</miage:heures>
				</miage:module>
			</miage:UE>
		</miage:semestre>
		<miage:semestre numéro="S2">
			<miage:UE type="obligatoire">
				<miage:intitulé>Finance</miage:intitulé>
				<miage:ECTS>6</miage:ECTS>
				<miage:module>
					<miage:intitulé>Mathématiques financières et choix d'investissement</miage:intitulé>
					<miage:heures>
						<miage:CM>30</miage:CM>
						<miage:TDTP>10</miage:TDTP>
					</miage:heures>
				</miage:module>
				<miage:module>
					<miage:intitulé>Choix financiers de la firme</miage:intitulé>
					<miage:heures>
						<miage:CM>30</miage:CM>
						<miage:TDTP>10</miage:TDTP>
					</miage:heures>
				</miage:module>
			</miage:UE>
			<miage:UE type="obligatoire">
				<miage:intitulé>Statistiques et Informatique</miage:intitulé>
				<miage:ECTS>6</miage:ECTS>
				<miage:module>
					<miage:intitulé>Statistiques</miage:intitulé>
					<miage:heures>
						<miage:CM>20</miage:CM>
						<miage:TDTP>24</miage:TDTP>
					</miage:heures>
				</miage:module>
				<miage:module>
					<miage:intitulé>Informatique niveau 6 (CSI)</miage:intitulé>
					<miage:heures>
						<miage:CM>20</miage:CM>
						<miage:TDTP>24</miage:TDTP>
					</miage:heures>
				</miage:module>
			</miage:UE>
			<miage:UE type="obligatoire">
				<miage:intitulé>MIAGE 3</miage:intitulé>
				<miage:ECTS>6</miage:ECTS>
				<miage:module>
					<miage:intitulé>Systèmes d'exploitation et architectures des ordinateurs</miage:intitulé>
					<miage:heures>
						<miage:CM>20</miage:CM>
						<miage:TDTP>20</miage:TDTP>
					</miage:heures>
				</miage:module>
				<miage:module>
					<miage:intitulé>Interfaces / VB</miage:intitulé>
					<miage:heures>
						<miage:CM>20</miage:CM>
						<miage:TDTP>20</miage:TDTP>
					</miage:heures>
				</miage:module>
			</miage:UE>
			<miage:UE type="obligatoire">
				<miage:intitulé>MIAGE 4</miage:intitulé>
				<miage:ECTS>6</miage:ECTS>
				<miage:module>
					<miage:intitulé>Recherche opérationnelle</miage:intitulé>
					<miage:heures>
						<miage:CM>15</miage:CM>
						<miage:TDTP>10</miage:TDTP>
					</miage:heures>
				</miage:module>
				<miage:module>
					<miage:intitulé>Stage</miage:intitulé>
					<miage:heures>
						<miage:CM>0</miage:CM>
						<miage:TDTP>0</miage:TDTP>
					</miage:heures>
				</miage:module>
			</miage:UE>
		</miage:semestre>
	</miage:formation>
	<miage:formation niveau="M1">
